sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - npm i npm -g
  - npm i dockyard@latest

script:
  - npm i
  - npm run build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - dockyard build image --repo=arobson --name=etcdeck --tags=lm

node_js:
  - "6"
