sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - npm i npm -g
  - npm i @npm-wharf/shipwright@latest

script:
  - npm i
  - npm run build
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=etcdeck --tags=lm,v,miv --cache-from-latest

node_js:
  - "8"
